// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Pivot.Infra.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190328221120_CorrigeUsuarioAlteracao")]
    partial class CorrigeUsuarioAlteracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Atividade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<long>("RamoId");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.HasIndex("RamoId");

                    b.ToTable("Atividade");
                });

            modelBuilder.Entity("Domain.Cidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<long>("EstadoId");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("Domain.Contato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo");

                    b.Property<long>("CidadeId");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<long>("MarcaId");

                    b.Property<string>("Nome");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("Domain.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContatoId");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Endereco");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("Domain.Estado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<string>("Sigla");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Domain.Grafia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<long>("MarcaId");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Grafia");
                });

            modelBuilder.Entity("Domain.Marca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Abrangencia");

                    b.Property<long>("AtividadeId");

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<int>("FaixaEtaria");

                    b.Property<string>("Logo");

                    b.Property<long>("MarcaAgrupadaId");

                    b.Property<int>("ModeloOperacional");

                    b.Property<int>("PricePoint");

                    b.Property<long>("RepresentanteId");

                    b.Property<string>("Url");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("MarcaAgrupadaId")
                        .IsUnique();

                    b.HasIndex("RepresentanteId");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("Domain.Ramo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.ToTable("Ramo");
                });

            modelBuilder.Entity("Domain.Telefone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContatoId");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Numero");

                    b.Property<int>("UsuarioAlteracaoId");

                    b.Property<string>("UsuarioAlteracaoLogin");

                    b.Property<int>("UsuarioCriacaoId");

                    b.Property<string>("UsuarioCriacaoLogin");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Domain.Atividade", b =>
                {
                    b.HasOne("Domain.Ramo", "Ramo")
                        .WithMany()
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Cidade", b =>
                {
                    b.HasOne("Domain.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Contato", b =>
                {
                    b.HasOne("Domain.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Email", b =>
                {
                    b.HasOne("Domain.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Grafia", b =>
                {
                    b.HasOne("Domain.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Marca", b =>
                {
                    b.HasOne("Domain.Atividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Marca", "MarcaAgrupada")
                        .WithOne()
                        .HasForeignKey("Domain.Marca", "MarcaAgrupadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Marca", "Representante")
                        .WithMany()
                        .HasForeignKey("RepresentanteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Telefone", b =>
                {
                    b.HasOne("Domain.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
